version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node

    steps:
      - checkout
      - run:
          name: Install Cucumber
          command: gem install cucumber
      - run:
          name: install the gem
          command: bundle
      - run:
          name: install brew
          command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - run:
          name: install chromedriver
          command: brew cask install chromedriver
      - run:
          name: run tests
          command: cucumber
      - run:
          name: Save test results
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
          when: always

      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber