version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.7-jessie-node-browsers

    steps:
      - checkout
      - run:
          name: Install Cucumber
          command: gem install cucumber
      - run:
          name: install the gem
          command: bundle
      - run:
          name: run tests
          command: cucumber
      - run:
          name: Save test results
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
          when: always

      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber