version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node

    steps:
      - checkout
      - run:
          name: Install Cucumber
          command: gem install cucumber
      - run:
          name: Install Selenium-Webdriver
          command: gem install selenium-webdriver
      - run:
          name: install the gem
          command: bundle
      - run:
          name: Download latest version of chromedriver
          command: wget "https://chromedriver.storage.googleapis.com/2.46/chromedriver_mac64.zip"

      - run:
          name: Unzip chromedriver
          command: sudo unzip chromedriver_mac64.zip
    
      - run:
          name: Move chromedriver
          command: sudo mv chromedriver /usr/local/bin/chromedriver

      - run:
          name: Change permission of chromedriver
          command: sudo chown root:root /usr/local/bin/chromedriver

      - run:
          name: Change permission of chromedriver
          command: sudo chmod +x /usr/local/bin/chromedriver
      - run:
          name: check chromedriver
          command: chromedriver --version
      - run:
          name: run tests
          command: cucumber
      - run:
          name: Save test results
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format junit --out ~/cucumber/junit.xml
          when: always

      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber